name: Staff
main: fr.nessar.Staff
description: Staff plugin.
version: 1
api-version: 1.8.8
commands:
  staff:
    description: enable staff mod
    permission: staff
    usage: "Usage: /<command>"
  freeze:
    aliases: [block]
    description: freeze the target
    permission: staff.freeze
    usage: "Usage: /<command> <target>"
  unfreeze:
    aliases: [defreeze, unblock, free]
    description: freeze the target
    permission: staff.unfreeze
    usage: "Usage: /<command> <target>"
  report:
    description: freeze the target
    permission: staff.report
    usage: "Usage: /<command> <target> (reason)"
  ticket:
    description: Ask help from moderation
    permission: staff.ticket
    usage: "Usage: /<command> <message>"
  tempban:
    description: Ban temporarily a player
    permission: staff.tempban
    usage: "Usage: /<command> <player> [time] (reason)"
  permaban:
    description: ban permanently a player
    permission: staff.permaban
    usage: "Usage: /<command> <player> (reason)"
  tempmute:
    description: Mute temporarily a player
    permission: staff.tempmute
    usage: "Usage: /<command> <player> [time] (reason)"
  permamute:
    description: mute permanently a player
    permission: staff.permamute
    usage: "Usage: /<command> <player> (reason)"
  tempreport:
    description: block report from a player temporarily
    permission: staff.tempreport
    usage: "Usage: /<command> <player> [time] (reason)"
  permareport:
    description: block report from a player
    permission: staff.permareport
    usage: "Usage: /<command> <player> (reason)"
  tempticket:
    description: block ticket from a player temporarily
    permission: staff.tempticket
    usage: "Usage: /<command> <player> [time] (reason)"
  permaticket:
    description: block ticket from a player
    permission: staff.permaticket
    usage: "Usage: /<command> <player> (reason)"
permissions:
  staff:
    description: allow base command staff
    default: op
