name: Staff
main: fr.nessar.Staff
description: Staff plugin.
version: 1
api-version: 1.8.8
commands:
  staff:
    description: enable staff mod
    permission: staff
    usage: "Usage: /<command>"
  freeze:
    aliases: [block]
    description: freeze the target
    permission: staff.freeze
    usage: "Usage: /<command> <target>"
  unfreeze:
    aliases: [defreeze, unblock, free]
    description: freeze the target
    permission: staff.unfreeze
    usage: "Usage: /<command> <target>"
  report:
    description: freeze the target
    permission: staff.report
    usage: "Usage: /<command> <target> (reason)"
  ticket:
    description: Ask help from moderation
    permission: staff.ticket
    usage: "Usage: /<command> <message>"
  tempban:
    description: Ban temporarily a player
    permission: staff.tempban
    usage: "Usage: /command <player> [time] (reason)"
permissions:
  staff:
    description: allow base command staff
    default: op
